/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mityushov.SimpleJavaTestFramework;

public class App {
    public static void main(String[] args) {
        TestLauncher.startTest("com.mityushov.SimpleJavaTestFramework.AppTest");
    }
}
