/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mityushov.SimpleJavaTestFramework;

import com.mityushov.SimpleJavaTestFramework.annotations.*;

public class AppTest {

    @Before
    public void setUp() {
        System.out.println("Before");
    }

    @Test
    public void shouldPrintTest1() {
        System.out.println("test1");
    }

    @Test
    public void shouldPrintTest2() {
        System.out.println("test2");
        throw new RuntimeException();
    }

    @After
    public void tearDown() {
        System.out.println("After");
    }

}
